// <auto-generated />
namespace _3whisky.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ImageUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201404271756320_ImageUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
